openapi: 3.1.0
info:
  title: Personal Fitness Agent API
  version: 1.0.0
  description: API for logging and retrieving fitness data (strength sets, workouts, readiness, etc.).
servers:
  - url: https://gpt-proxy-danlevitt.vercel.app?x-vercel-protection-bypass=1CQBplG678yMDnEwGaTSEojJb2h1uUMm
paths:
  "/api/strength":
    post:
      summary: Log a strength-training set
      operationId: logStrengthSet
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StrengthSet'
      responses:
        "200":
          description: Successfully stored the set
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  stored:
                    $ref: '#/components/schemas/StrengthSet'
  "/api/trends":
    get:
      operationId: getWorkoutTrends
      summary: Get weekly workout trends
      security:
        - ApiKeyAuth: []
      parameters:
        - name: weeks
          in: query
          description: Number of recent ISO weeks to include (default 4)
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Weekly trend summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  weeks:
                    type: array
                    items:
                      type: object
                      properties:
                        week: { type: string, example: "2025-W27" }
                        metrics:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              tonnage: { type: number }
                              distance: { type: number }
                              duration: { type: number }
                              sessions: { type: integer }
                  progressing:
                    type: array
                    items: { type: string }
                  stalling:
                    type: array
                    items: { type: string }
  "/api/workout":
    post:
      summary: Log an endurance or cross-training workout (run, bike, swim, etc.)
      operationId: logWorkout
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
      responses:
        "200":
          description: Successfully stored the workout
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  stored:
                    $ref: '#/components/schemas/Workout'
  "/api/run-trends":
    get:
      summary: Get weekly running trends
      operationId: getRunTrends
      security:
        - ApiKeyAuth: []
      parameters:
        - name: weeks
          in: query
          description: Number of ISO weeks to include (default 4)
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Weekly running trend summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  weeks:
                    type: array
                    items:
                      type: object
                      properties:
                        week: { type: string, example: "2025-W27" }
                        distance: { type: number, description: "Total miles" }
                        duration: { type: number, description: "Total minutes" }
                        sessions: { type: integer }
                        avgPace: { type: number, nullable: true, description: "Minutes per mile" }
                  progressing:
                    type: boolean
  "/api/cycle-trends":
    get:
      summary: Get weekly cycling trends
      operationId: getCycleTrends
      security:
        - ApiKeyAuth: []
      parameters:
        - name: weeks
          in: query
          description: Number of ISO weeks to include (default 4)
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Weekly cycling trend summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  weeks:
                    type: array
                    items:
                      type: object
                      properties:
                        week: { type: string, example: "2025-W27" }
                        distance: { type: number, description: "Total miles" }
                        duration: { type: number, description: "Total minutes" }
                        sessions: { type: integer }
                        avgSpeed: { type: number, nullable: true, description: "Mph" }
                  progressing:
                    type: boolean
  "/api/swim-trends":
    get:
      summary: Get weekly swimming trends
      operationId: getSwimTrends
      security:
        - ApiKeyAuth: []
      parameters:
        - name: weeks
          in: query
          description: Number of ISO weeks to include (default 4)
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Weekly swimming trend summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  weeks:
                    type: array
                    items:
                      type: object
                      properties:
                        week: { type: string, example: "2025-W27" }
                        distance: { type: number, description: "Total miles" }
                        duration: { type: number, description: "Total minutes" }
                        sessions: { type: integer }
                        avgPace: { type: number, nullable: true, description: "Minutes per mile" }
                  progressing:
                    type: boolean
  "/api/training-plan":
    get:
      summary: Get the latest training plan
      operationId: getTrainingPlan
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Latest training plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  plan:
                    $ref: '#/components/schemas/TrainingPlan'
    post:
      summary: Create a new training plan
      operationId: createTrainingPlan
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingPlan'
      responses:
        "200":
          description: Training plan created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  message:
                    type: string
                    example: Training plan created successfully
                  plan:
                    $ref: '#/components/schemas/TrainingPlan'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        Fitness Agent API key. Also requires x-vercel-protection-bypass header.
        Example value: super-secret-123
  schemas:
    StrengthSet:
      type: object
      required: [date, exercise, setNumber, reps, weight]
      properties:
        date:
          type: string
          description: ISO date (YYYY-MM-DD)
          example: "2025-07-12"
        exercise:
          type: string
          example: Squat
        setNumber:
          type: integer
          example: 1
        reps:
          type: integer
          example: 8
        weight:
          type: number
          example: 135
        rpe:
          type: number
          nullable: true
          example: 7
        notes:
          type: string
          nullable: true
          example: "test via ChatGPT Action"
    Workout:
      type: object
      required: [date, type]
      properties:
        date:
          type: string
          description: ISO date (YYYY-MM-DD)
          example: "2025-07-12"
        type:
          type: string
          description: Activity type (Run, Bike, Swim, etc.)
          example: Run
        duration:
          type: number
          description: Minutes
          example: 45
        distance:
          type: number
          description: Kilometers
          example: 10
        calories:
          type: number
          example: 500
        sets:
          type: integer
          nullable: true
          example: 3
        weight:
          type: number
          nullable: true
          example: 0
        reps:
          type: integer
          nullable: true
          example: 0
        notes:
          type: string
          nullable: true
          example: "Afternoon tempo run"
    TrainingPlan:
      type: object
      required: [weekStart, weekEnd, planType]
      properties:
        weekStart:
          type: string
          format: date
          description: Start date of the training week (ISO format)
          example: "2025-01-13"
        weekEnd:
          type: string
          format: date
          description: End date of the training week (ISO format)
          example: "2025-01-19"
        planType:
          type: string
          description: Type of training plan (build, maintain, recovery, race-prep)
          example: "build"
        swimSessions:
          type: integer
          description: Number of swim sessions planned
          example: 2
        bikeSessions:
          type: integer
          description: Number of bike sessions planned
          example: 3
        runSessions:
          type: integer
          description: Number of run sessions planned
          example: 2
        strengthSessions:
          type: integer
          description: Number of strength sessions planned
          example: 2
        ptSessions:
          type: integer
          description: Number of physical therapy sessions planned
          example: 3
        recoverySessions:
          type: integer
          description: Number of recovery/rest sessions planned
          example: 1
        totalVolume:
          type: integer
          description: Total number of sessions planned
          example: 13
        intensity:
          type: string
          description: Overall intensity level (low, moderate, high)
          example: "moderate"
        notes:
          type: string
          nullable: true
          description: Additional notes about the training plan
          example: "Focus on building endurance base" 