openapi: 3.1.0
info:
  title: Personal Fitness Agent API
  version: 1.0.0
  description: API for logging and retrieving fitness data (strength sets, workouts, readiness, etc.).
servers:
  - url: https://gpt-proxy-ig5qo0hbt-dans-projects-19e6c8d0.vercel.app
paths:
  /api/strength:
    post:
      summary: Log a strength-training set
      operationId: logStrengthSet
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StrengthSet'
      responses:
        "200":
          description: Successfully stored the set
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  stored:
                    $ref: '#/components/schemas/StrengthSet'
  "/api/trends?x-vercel-protection-bypass=1CQBplG678yMDnEwGaTSEojJb2h1uUMm":
    get:
      operationId: getWorkoutTrends
      summary: Get weekly workout trends
      security:
        - ApiKeyAuth: []
      parameters:
        - name: weeks
          in: query
          description: Number of recent ISO weeks to include (default 4)
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Weekly trend summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  weeks:
                    type: array
                    items:
                      type: object
                      properties:
                        week: { type: string, example: "2025-W27" }
                        metrics:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              tonnage: { type: number }
                              distance: { type: number }
                              duration: { type: number }
                              sessions: { type: integer }
                  progressing:
                    type: array
                    items: { type: string }
                  stalling:
                    type: array
                    items: { type: string }
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: |
        Fitness Agent API key. Also requires x-vercel-protection-bypass header.
        Example value: super-secret-123
  schemas:
    StrengthSet:
      type: object
      required: [date, exercise, setNumber, reps, weight]
      properties:
        date:
          type: string
          description: ISO date (YYYY-MM-DD)
          example: "2025-07-12"
        exercise:
          type: string
          example: Squat
        setNumber:
          type: integer
          example: 1
        reps:
          type: integer
          example: 8
        weight:
          type: number
          example: 135
        rpe:
          type: number
          nullable: true
          example: 7
        notes:
          type: string
          nullable: true
          example: "test via ChatGPT Action" 