const GoogleSheets = require('../integrations/google-sheets');

/**
 * Append one workout entry (run, bike, swim, etc.) to the Workouts tab in Google Sheets.
 * @param {Object} params
 * @param {string} params.date – ISO yyyy-mm-dd or today
 * @param {string} params.type – Activity type (e.g. Run, Bike)
 * @param {number} [params.duration] – minutes
 * @param {number} [params.distance] – kilometers
 * @param {number} [params.calories]
 * @param {number} [params.sets]
 * @param {number} [params.weight]
 * @param {number} [params.reps]
 * @param {string} [params.notes]
 */
module.exports = async function logWorkout(params = {}) {
  const required = ['date', 'type'];
  for (const f of required) {
    if (params[f] === undefined || params[f] === null || params[f] === '') {
      throw new Error(`Missing required field: ${f}`);
    }
  }

  const gs = new GoogleSheets();
  await gs.initialize();

  const workoutDetail = {
    id: '', // leave blank – generated by sheet if needed
    date: new Date(params.date),
    type: params.type,
    duration: params.duration || '',
    distance: params.distance || '',
    calories: params.calories || '',
    source: 'ChatGPT',
    sets: params.sets || '',
    weight: params.weight || '',
    reps: params.reps || '',
    notes: params.notes || ''
  };

  await gs.storeWorkout(workoutDetail);
  return { status: 'ok', stored: workoutDetail };
}; 